package com.xxy.seckill.seckillmanagement.dao;

import com.xxy.seckill.seckillmanagement.dataobject.OrderDAO;
import org.springframework.stereotype.Component;

@Component
public interface OrderDAOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat May 11 23:25:25 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat May 11 23:25:25 CST 2019
     */
    int insert(OrderDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat May 11 23:25:25 CST 2019
     */
    int insertSelective(OrderDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat May 11 23:25:25 CST 2019
     */
    OrderDAO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat May 11 23:25:25 CST 2019
     */
    int updateByPrimaryKeySelective(OrderDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat May 11 23:25:25 CST 2019
     */
    int updateByPrimaryKey(OrderDAO record);
}