package com.xxy.seckill.seckillmanagement.dao;

import com.xxy.seckill.seckillmanagement.dataobject.SequenceDAO;
import org.springframework.stereotype.Component;

@Component
public interface SequenceDAOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun May 12 15:30:45 CST 2019
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun May 12 15:30:45 CST 2019
     */
    int insert(SequenceDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun May 12 15:30:45 CST 2019
     */
    int insertSelective(SequenceDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun May 12 15:30:45 CST 2019
     */
    SequenceDAO selectByPrimaryKey(String name);

    SequenceDAO getSequenceByName(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun May 12 15:30:45 CST 2019
     */
    int updateByPrimaryKeySelective(SequenceDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun May 12 15:30:45 CST 2019
     */
    int updateByPrimaryKey(SequenceDAO record);
}