package com.xxy.seckill.seckillmanagement.dataobject;

public class DictDAO extends DictDAOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_dict.name
     *
     * @mbg.generated Sun Jun 09 16:03:28 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_dict.memo
     *
     * @mbg.generated Sun Jun 09 16:03:28 CST 2019
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_dict.state
     *
     * @mbg.generated Sun Jun 09 16:03:28 CST 2019
     */
    private Byte state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_dict.name
     *
     * @return the value of code_dict.name
     *
     * @mbg.generated Sun Jun 09 16:03:28 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_dict.name
     *
     * @param name the value for code_dict.name
     *
     * @mbg.generated Sun Jun 09 16:03:28 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_dict.memo
     *
     * @return the value of code_dict.memo
     *
     * @mbg.generated Sun Jun 09 16:03:28 CST 2019
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_dict.memo
     *
     * @param memo the value for code_dict.memo
     *
     * @mbg.generated Sun Jun 09 16:03:28 CST 2019
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_dict.state
     *
     * @return the value of code_dict.state
     *
     * @mbg.generated Sun Jun 09 16:03:28 CST 2019
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_dict.state
     *
     * @param state the value for code_dict.state
     *
     * @mbg.generated Sun Jun 09 16:03:28 CST 2019
     */
    public void setState(Byte state) {
        this.state = state;
    }
}